# This Fig configuration file is meant to be used with fig-env. See
# https://bitbucket.org/springersbm/fig-env.

code:
  image: te-docker.docker-registry.tools.springer-sbm.com/fig-env-node
  dns: *DNS
  volumes:
    - ..:/home/dev/code

deploy:
  image: te-docker.docker-registry.tools.springer-sbm.com/fig-env-deploy-to-cf
  dns: *DNS
  volumes:
    - ..:/home/dev/code
